-- MySQL Script generated by MySQL Workbench
-- 06/26/17 20:24:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vegetaurante
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vegetaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vegetaurante` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `vegetaurante` ;

-- -----------------------------------------------------
-- Table `vegetaurante`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vegetaurante`.`endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(150) NOT NULL,
  `bairro` VARCHAR(60) NOT NULL,
  `cidade` VARCHAR(80) NOT NULL,
  `cep` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vegetaurante`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vegetaurante`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `telefone` VARCHAR(15) NULL,
  `celular` VARCHAR(16) NULL,
  `idEndereco` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_endereco1_idx` (`idEndereco` ASC),
  CONSTRAINT `fk_usuario_endereco1`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `vegetaurante`.`endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vegetaurante`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vegetaurante`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_cliente_usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `vegetaurante`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vegetaurante`.`prato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vegetaurante`.`prato` (
  `idPrato` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(100) NULL,
  `preco` FLOAT NULL,
  `imgSopa` VARCHAR(100) NULL,
  PRIMARY KEY (`idPrato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vegetaurante`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vegetaurante`.`funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  INDEX `fk_funcionario_usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_funcionario_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `vegetaurante`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vegetaurante`.`bandeira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vegetaurante`.`bandeira` (
  `idBandeira` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idBandeira`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vegetaurante`.`cartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vegetaurante`.`cartao` (
  `idCartao` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(50) NOT NULL,
  `codigoSeguranca` INT NOT NULL,
  `idBandeira` INT NOT NULL,
  PRIMARY KEY (`idCartao`),
  INDEX `fk_cartao_bandeira2_idx` (`idBandeira` ASC),
  CONSTRAINT `fk_cartao_bandeira2`
    FOREIGN KEY (`idBandeira`)
    REFERENCES `vegetaurante`.`bandeira` (`idBandeira`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vegetaurante`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vegetaurante`.`pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `idFuncionario` INT NOT NULL,
  `dataPedido` DATETIME NULL,
  `status` VARCHAR(45) NULL,
  `total` FLOAT NULL,
  `formaPagamento` VARCHAR(45) NULL,
  `idCartao` INT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_pedido_cliente1_idx` (`idCliente` ASC),
  INDEX `fk_pedido_funcionario1_idx` (`idFuncionario` ASC),
  INDEX `fk_pedido_cartao1_idx` (`idCartao` ASC),
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `vegetaurante`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_funcionario1`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `vegetaurante`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_cartao1`
    FOREIGN KEY (`idCartao`)
    REFERENCES `vegetaurante`.`cartao` (`idCartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vegetaurante`.`item_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vegetaurante`.`item_pedido` (
  `idItemPedido` INT NOT NULL AUTO_INCREMENT,
  `idPedido` INT NOT NULL,
  `idMenu` INT NOT NULL,
  `quantidade` INT NULL,
  `subtotal` FLOAT NULL,
  PRIMARY KEY (`idItemPedido`),
  INDEX `fk_item_pedido_menu1_idx` (`idMenu` ASC),
  INDEX `fk_item_pedido_pedido1_idx` (`idPedido` ASC),
  CONSTRAINT `fk_item_pedido_menu1`
    FOREIGN KEY (`idMenu`)
    REFERENCES `vegetaurante`.`prato` (`idPrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_pedido_pedido1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `vegetaurante`.`pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
